### ISSUE TITLE
Problem with Xena-Master

### ISSUE THREAD

**Issue by acidburn1979** [Jonatino/Xena#38]
Exception in thread "main" java.lang.IllegalStateException: Can not find offset inside of engine.dll with pattern [5, 0, 0, 0, 0, -61, -52, -52, -52, -52, -52, -52, -52, -128, 61]
        at org.xena.offsets.misc.PatternScanner.byPattern(PatternScanner.java:55)
        at org.xena.offsets.misc.PatternScanner.byPattern(PatternScanner.java:38)
        at org.xena.offsets.offsets.EngineOffsets.load(EngineOffsets.kt:57)
        at org.xena.offsets.OffsetManager.loadOffsets(OffsetManager.java:83)
        at org.xena.offsets.OffsetManager.initAll(OffsetManager.java:68)
        at org.xena.Main.main(Main.java:32)
Press any key to continue . . .

**Comment by Chipaaa** [comment]
Jip Xena is broken after new update :(

**Comment by acidburn1979** [comment]
Thanks a lot Chipaaa. Will there be an update to it?Sent from my Samsung Galaxy smartphone.<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Chipaaa <notifications@github.com> </div><div>Date: 28/11/2019  10:06  (GMT+04:00) </div><div>To: Jonatino/Xena <Xena@noreply.github.com> </div><div>Cc: acidburn1979 <benoit@intnet.mu>, Author <author@noreply.github.com> </div><div>Subject: Re: [Jonatino/Xena] Problem with Xena-Master (#38) </div><div>
</div>Jip Xena is broken after new update :(

**Comment by NeariX67** [comment]
I fixed it:
Change in EngineOffsets.kt the following (should be line 57:)
replace
`dwMapDirectory = byPattern(engineModule(), 0x1, 0x0, PatternScanner.READ, 0x05, 0x00, 0x00, 0x00, 0x00, 0xC3, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0x80, 0x3D)`
with
`dwMapDirectory = 0x188`

this should fix it (works for me) until Jonatino pulbished a final version
